### ISSUE TITLE
Code reviews Pairs

### ISSUE THREAD

**Issue by hendridg** [andres-condezo/Portfolio#10]
# Code reviews pairs :eyes:

**Comment by hendridg** [comment]
## Hi @andres-condezo,

Great job, amazing animation!, Congratulations! 🎉 :fire: :fire: :fire: 

![](https://media1.giphy.com/media/d31w24psGYeekCZy/giphy.gif)


## Optional suggestions
In the file `index.html`, I would suggest changing the class `.btn` to a class with a more specific behavior, maybe you can change it to `.btn-transitions`

**Comment by eduardosancho** [comment]
Great job on animating your webpage ⭐⭐⭐⭐⭐

> 3a1585ecb1af10989f4e8d84472f300928d587bf
This is an optional suggestion, to make your portfolio even cooler. 😎 
Tip, check the following properties:
-animation-iteration-count: infinite; ♾️ 
-animation-direction: alternate;

I believe this article can also help you out:
https://www.geeksforgeeks.org/css-pulse-animation/

Again, great work and c ongratulations! 🎉

**Comment by andres-condezo** [comment]
Thanks @hendridg @eduardosancho , you are right I will make the changes immediately.

**Comment by Jord4N-AC** [comment]
As I could appreciate, most our your portfolio looks nice, I'll just highlight some good points: 👏👏👏
- Animations well applied
- Transitions well applied
- @media queries well applied
- Good use of HTML and CSS good practices

You did an amazing job, congratulations, keep soaring higher.
