### ISSUE TITLE
Morning Peer-to-Peer code review

### ISSUE THREAD

**Issue by Sahar-AbdelSamad** [andres-condezo/Portfolio#13]
# Hi @andres-condezo  👋🏻 

## To highlight 👍🏻  ##  
:heavy_check_mark: The project is looking great
:heavy_check_mark: You followed the Figma template perfectly

## Suggestions :stars: ##
- [ ] optionalYou can add the HTML inside the HTML file or create it with JavaScript

<img src="https://media1.giphy.com/media/VBc6l3CqQonqo/giphy.gif"/>

Cheers and Happy coding! 🎉🎉🎉

**Comment by andres-condezo** [comment]
Thanks for the feedback :+1:
